// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pdf_search.Data;

#nullable disable

namespace PdfSearch.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pdf_search.Data.Submissions", b =>
                {
                    b.Property<string>("batch")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("date")
                        .HasColumnType("date");

                    b.Property<string>("q1")
                        .HasColumnType("text");

                    b.Property<string>("q10")
                        .HasColumnType("text");

                    b.Property<string>("q2")
                        .HasColumnType("text");

                    b.Property<string>("q3")
                        .HasColumnType("text");

                    b.Property<string>("q4")
                        .HasColumnType("text");

                    b.Property<string>("q5")
                        .HasColumnType("text");

                    b.Property<string>("q6")
                        .HasColumnType("text");

                    b.Property<string>("q7")
                        .HasColumnType("text");

                    b.Property<string>("q8")
                        .HasColumnType("text");

                    b.Property<string>("q9")
                        .HasColumnType("text");

                    b.Property<string>("wholeDoc")
                        .HasColumnType("text");

                    b.HasKey("batch", "name");

                    b.ToTable("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
